version: "3.9"

networks:
  default:
    external: true
    name: payment_integration-network

services:

  postgres:
    image: postgres:14.0
    container_name: payment_integration-postgres
    restart: unless-stopped
    command: postgres -c 'max_connections=200'
    ports:
      - "10432:5432"
    environment:
      POSTGRES_PASSWORD: "111"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
